os: windows
language: shell

env:
  global:
    - DEPLOY_VERSION=$TRAVIS_TAG
    - secure: iggJlcOL4PzoT+1CzaBaB1153d5Pj8UlGstinflBmurxz3arMBJ6kFSFvhZjl22GCwaiPDQt8VWV4uTfzFxrQoKGDZ2yu3fofR/HU+qX/Vy8lkXK98g0JJB30oM0aK2wwlbGgq/ddEBG6fqXxQt/SrfTmOu1cVSd31/w1hR5gP4=

install:
  - dotnet restore src

script:
  - dotnet build src
  - dotnet test src

before_deploy:
  - dotnet pack -c Release /p:PackageVersion=$DEPLOY_VERSION /p:Version=$DEPLOY_VERSION /p:AssemblyVersion=$DEPLOY_VERSION

deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push bin\Release\stream-net.*.nupkg -k $NUGET_KEY -s https://api.nuget.org/v3/index.json
  on:
    repo: GetStream/stream-net
    tags: true
