version: 2.0.5-{build}
image: Visual Studio 2017
configuration: Release

init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq 'true') {
       Update-AppveyorBuild -Version "${env:APPVEYOR_REPO_TAG_NAME}"
    }

dotnet_csproj:
  patch: true
  file: '**\stream-net.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- appveyor-retry dotnet restore .\src -v Minimal

build_script:
- dotnet build .\src

build:
  publish_nuget: true

deploy:
  provider: NuGet
  server:
  api_key:
    secure: m6faziM7bb+vGkLObwOvwBj9D6fZ8CJ58ZkPHqVKsPONTGcB/gJt7ZL6bVl/dS2a
  skip_symbols: false
  symbol_server:
  artifact: /.*\.nupkg/
  on:
    APPVEYOR_REPO_TAG: true

after_test:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
