version: 2.0.{build}
image: Visual Studio 2017

before_build:
- appveyor-retry dotnet restore .\src -v Minimal
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq 'true') {
       Update-AppveyorBuild -Version "${env:APPVEYOR_REPO_TAG_NAME}"
    }

build_script:
- dotnet build .\src

deploy:
  provider: NuGet
  server:
  api_key:
    secure: aaaaaa__WeDMJfGDHtrR530W7XTocd5nguQXaY5YXrsjdkPwA9J1WudU9m7Y7MU1Kp/L9KtZ
  skip_symbols: false
  symbol_server:
  artifact: /.*\.nupkg/
  on:
    APPVEYOR_REPO_TAG: true

on_finish:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
